#!/bin/bash
ruby start.rb data/data_M1.csv
ruby start.rb data/data_M2.csv
ruby start.rb data/data_M3.csv
ruby start.rb data/data_M4.csv
ruby start.rb data/data_M5.csv
ruby start.rb data/data_M6.csv
ruby start.rb data/data_M7.csv
ruby start.rb data/data_M8.csv
ruby start.rb data/data_M9.csv
ruby start.rb data/data_M10.csv
ruby start.rb data/data_M11.csv
ruby start.rb data/data_M12.csv
ruby start.rb data/data_M13.csv
ruby start.rb data/data_M14.csv
ruby start.rb data/data_M15.csv
ruby start.rb data/data_M16.csv
ruby start.rb data/data_M17.csv
ruby start.rb data/data_M18.csv
ruby start.rb data/data_M19.csv
ruby start.rb data/data_M20.csv
